export const LOGINREQUEST = "LOGINREQUEST";
export const LOGINSUCCESS = "LOGINSUCCESS";
export const LOGINFAILURE = "LOGINFAILURE";

export const SIGNUPREQUEST = "SIGNUPREQUEST";
export const SIGNUPSUCCESS = "SIGNUPSUCCESS";
export const SIGNUPFAILURE = "SIGNUPFAILURE";

export const PROJECTSUCCESS = "PROJECTSUCCESS";
export const PROJECTFAILURE = "PROJECTFAILURE";
export const PROJECTDELETE = "PROJECTDELETE";

export const CURRPROJECTREQUEST = "CURRPROJECTREQUEST" 
export const CURRPROJECTPROCESS = "CURRPROJECTPROCESS" 
export const CURRPROJECTSUCCESS = "CURRPROJECTSUCCESS"
export const CURRPROJECTFAILURE = "CURRPROJECTFAILURE" 

export const TASKS = "TASKS"

export const USER = "USER";
export const ALLUSER = "ALLUSER";

export const LOGOUT = "LOGOUT";

export const GUIDE = "GUIDE";

export const TEMPLATE = 'TEMPLATE';